### ISSUE TITLE
Add `begin_chain` function to contract

### ISSUE THREAD

**Issue by frankbraun** [aurora-is-near/aurora-engine#1]
For the [evm-bully](https://github.com/aurora-is-near/evm-bully) we need a `begin_chain` function.
The function should allow to set the account balances in the genesis state and should only be available in a testing version of the contract.

**Comment by artob** [comment]
@frankbraun Commit 526005ddbfcf198f469ad3ccdf81e64b45f5b098 added an initial parameter definition for `begin_chain`:

https://github.com/aurora-is-near/aurora-engine/blob/78c7c1f3d34b4da028cdf5f59a27bcf184494faf/src/types.rs#L44-L48

Note that the input to the `begin_chain` function is Borsh-encoded, not JSON-encoded.

I'm still working on figuring out a workable Borsh encoding for setting genesis block balances.

If more scalar parameters beyond `chain_id` are needed, add them in a PR.

**Comment by frankbraun** [comment]
This needs to be put behind a feature flag and, as @ilblackdragon noted, should only be callable by the owner.

@artob: You mentioned that you already have some code for this?

**Comment by artob** [comment]
> @artob: You mentioned that you already have some code for this?

I've restored the basic `begin_chain` functionality in 1458997. It had broken when #6 was merged.

**Comment by joshuajbouw** [comment]
Isn't this closed now?

**Comment by artob** [comment]
@frankbraun Can this be closed? Please close issues when they are done.

**Comment by frankbraun** [comment]
Sorry, this got buried in GitHub notifications.
