### ISSUE TITLE
Implement base token using FT standard

### ISSUE THREAD

**Issue by artob** [aurora-is-near/aurora-engine#10]
https://github.com/near/near-evm/issues/64#issue-813489281
> This modifies functions like `deposit(receiver, amount)` and `withdraw(receiver, amount)` to only be allowed to be called from specific contract. This requires a bit more specification though.
> 
> Otherwise make sure that interface compliant with NEP-141 standard.

**Comment by mrLSD** [comment]
#22

**Comment by joshuajbouw** [comment]
This can be closed as this has been completed in #22.
