### ISSUE TITLE
Correctly handle gas limits on transactions

### ISSUE THREAD

**Issue by birchmd** [aurora-is-near/aurora-engine#119]
Presently we allow any gas limit to be specified on a transaction passed to `submit`. This is incorrect behaviour relative to Ethereum where there is a notion of "intrinsic gas".

The current behaviour is causing a problem because (a) it is an incompatibility with Ethereum, and we are always pushing for maximum compatibility; and (b) the relayer has trouble handling transactions with 0 gas limit (and these would be invalid transactions if we had the correct logic in the Engine).

This issue is completed when the following is done:

- [ ] Have a function which computes "intrinsic gas" for transactions
- [ ] Verify all transactions passed via `submit` have a gas limit greater than or equal to the intrinsic gas
- [ ] Respect the gas limit when processing transactions passed to `submit` (i.e. fail with OOG when computation exceeds limit)

References:

* https://github.com/ethereum/go-ethereum/blob/master/core/state_transition.go#L259
* https://github.com/ethereum/go-ethereum/blob/master/core/state_transition.go#L114
* https://github.com/ethereum/yellowpaper/blob/master/Paper.tex#L593

**Comment by artob** [comment]
@birchmd  To sync with ongoing work in the relayer, the error code for this should be called `ERR_INTRINSIC_GAS`; this matches Geth's internal error enum `ErrIntrinsicGas` which in turn produces the external error message "intrinsic gas too low".

**Comment by birchmd** [comment]
Fixed in #123
