### ISSUE TITLE
Fix test_meta_parsing test case

### ISSUE THREAD

**Issue by artob** [aurora-is-near/aurora-engine#13]
Please fix the failing `test_meta_parsing` test case added in #6:
https://github.com/aurora-is-near/aurora-engine/runs/2214184828

**Comment by joshuajbouw** [comment]
Hmm, this is a bit interesting. I got past a few issues plaguing it already, and followed the EIP that references it. I don't see the test cases of what I should be putting in, and getting out in that reference though.
