### ISSUE TITLE
Refactoring: unwrap- and expect- related traits

### ISSUE THREAD

**Issue by sept-en** [aurora-is-near/aurora-engine#134]
Currently, we have `ExpectUtf8`, `SdkUnwrap`, `SdkExpect` defined in `src/lib.rs` and `src/types.rs` files.
It makes sense to move this instead to some specific module or even to `src/prelude.rs` (I'm not sure that `prelude` is a good place for it though as this will require importing `sdk` module).

**Comment by mrLSD** [comment]
@sept-en Currently it's part of `src/types.rs`, and it's good place. 
So I suggesting to close issue.

**Comment by sept-en** [comment]
Yes, makes sense, it was solved in recent PRs.
@mrLSD thanks for noticing that!
