### ISSUE TITLE
Add `evm-bully` tests to CI

### ISSUE THREAD

**Issue by frankbraun** [aurora-is-near/aurora-engine#139]
To prevent regressions and assure performance. They are pretty long running and need large test data sets, so probably we need something else for that than GitHub workflows. Details TBD.

**Comment by birchmd** [comment]
Yeah, this is a great idea! I think it is possible to set up custom runners for GH actions, so we could still write the test as an action, but run it on our own infrastructure if it's too big to GH.

If it takes a long time then we probably don't want to do it on every PR to develop. But we could do it on every PR to master, as well as on a schedule (e.g. once per day) to periodically look for regressions in develop.
