### ISSUE TITLE
Obtain new tps from running benchmarks with ecrecover host function

### ISSUE THREAD

**Issue by birchmd** [aurora-is-near/aurora-engine#169]
`ecrecover` is now in `nearcore` master branch. This means we can [run the benchmarks again](https://github.com/aurora-is-near/aurora-engine/pull/41#issuecomment-828526208) to see our new expected tps.

**Comment by birchmd** [comment]
Preliminary results (optimizations are still possible) from [this branch](https://github.com/birchmd/aurora-engine/tree/evm-benchmark-with-math-api) show

- Simple ETH transfer takes approx 7 NEAR Tgas
- ERC-20 token transfer takes approx 19 NEAR Tgas

Assuming Aurora gets its own shard with 1000 Tgas per block and NEAR maintains its block time of 1 second, then our theoretical TPS would be approx 140 for simple ETH transfers and approx 50 for ERC-20 token transfers.

cc @artob @djsatok

**Comment by djsatok** [comment]
@birchmd , thanks! Can you please do the benchmark for the Uniswap swap (~170k Eth Gas)?

**Comment by birchmd** [comment]
Current results (transfers taken from [`develop` branch](https://github.com/aurora-is-near/aurora-engine/tree/3532cb391b0369c07d760e5536996a4b4dfc25b1), uniswap is on a [separate branch](https://github.com/birchmd/aurora-engine/tree/4d0f5576bb3a90d8474ddb3824cc143561d4637a) because it required messing with dependency versions):

| Measurement           | NEAR gas (Tgas) | Throughput (tx/s assuming 1000 Tgas/s)  |
|-----------------------|-----------------|-----------------------------------------|
| Ether Transfer        | 6.64            | 151                                     |
| ERC-20 Transfer       | 12.9            | 77.5                                    |
| Uniswap Add liquidity | 217             | 4.61                                    |
| Uniswap Simple Swap   | 143             | 6.99                                    |

This is sufficient to close this issue. We can revisit benchmarks again if we make further performance improvements.
