### ISSUE TITLE
Extend JSON parser for integer types

### ISSUE THREAD

**Issue by mrLSD** [aurora-is-near/aurora-engine#176]
Currently, for JSON parser base number is f64.
We don't use negative integer numbers, so should be separated and implemented `JsonValue` entities:
* U8(u8)
* U64(u64)
* F64(f32)
JSON not supported `u128` type.

Entity `Number(f64)` should be removed.

Implement new Traits for parser and parser functions.

Rewrite tests for: `f64, u8, u64`

**Comment by mrLSD** [comment]
#141

**Comment by birchmd** [comment]
Done in #183
