### ISSUE TITLE
Measure the size of contract for JSON parser library: serde vs rjson

### ISSUE THREAD

**Issue by mrLSD** [aurora-is-near/aurora-engine#177]
Measure the size of contract for JSON parser library: `serde` vs `rjson`

We should determine what it for the release version.

What should be checked:
* measure current `rjosn` contract size
* change json parser to `serde` and measure new contract size (with removed `rjson`)

**Comment by mrLSD** [comment]
#141 #176

**Comment by birchmd** [comment]
Can we close this?
