### ISSUE TITLE
NEP141: `ft_resolve_transfer` compliance

### ISSUE THREAD

**Issue by sept-en** [aurora-is-near/aurora-engine#188]
According to the NEP141 standard, `ft_resolve_transfer` should return JSON instead of bytes as we do right now. This is needed to be fixed for the compliance with the standard.

**Comment by joshuajbouw** [comment]
This was investigated and it was found that the NEP-141 compliance is correct already. It returns as a `String` containing a value, not as JSON.

**Comment by mrLSD** [comment]
[NEP-141](https://github.com/near/NEPs/blob/master/specs/Standards/FungibleToken/Core.md#reference-level-explanation)

**Comment by sept-en** [comment]
@joshuajbouw I'd argue, as `ft_resolve_transfer` in bridge tokens (e.g. produced from `factory.bridge.near`) return the result as `String`, but in `aurora` case - we return bytes representation instead.

**Comment by mrLSD** [comment]
I think the issue should be closed. The issue title: " ft_resolve_transfer compliance". But we checked the code and it's related to NEP-141.
The description of the issue about JSON. But "ft_resolve_transfer" do not return JSON. But string.
So issue name and description don't relevant for the current NEP-141 implementation.

It should be opened new issues like: "ft_resolve_transfer return bytes instead string". And proof it.
And in the description, you should provide full instruction on how to reproduce it with the current `develop` branch. With result from near-cli, and link to explorer for transactions with new smartcontract.

Function `sdk::return_output` - always return bytes for any types. And current implementation return string is converted to bytes, as function `ft_balance_of` and others. Without full descriptions and examples of problems for `near-cli` and `explorer` the issue doesn't have value.

**Comment by mfornet** [comment]
@sept-en to avoid confusion it is better is you provide the line (context) where the implementation is wrong.

To avoid confusions, notice that the result is actually a string encoded as bytes, something like:

`b"\"80\""`

They are bytes, but when decoded is just a string that contains a number.
