### ISSUE TITLE
Measure view call limitations

### ISSUE THREAD

**Issue by birchmd** [aurora-is-near/aurora-engine#199]
Based on what I understand from @0x3bfc it is common for Ethereum dapps to take advantage of the fact that view calls on Ethereum are free (when called from externally owned accounts) and don't have stringent limits. However, on NEAR view calls have gas limits and apparently are easy to exceed with common patters (e.g. pagenation) used in Ethereum view calls. See for example https://github.com/aurora-is-near/aurora-relayer/issues/23#issuecomment-887360581

The purpose of this issue is to add benchmarks measuring NEAR gas usage for view calls into solidity smart contracts deployed on Aurora. These can be used to help us see progress as we attempt to optimize Aurora to be able to handle these calls without hitting NEAR gas limits.

**Comment by bowenwang1996** [comment]
I don't see a better solution other than increasing the view call gas limit on the rpc nodes. Since Aurora has its own rpc nodes, it should not be too hard to do.

**Comment by joshuajbouw** [comment]
Thanks for the input @bowenwang1996
