### ISSUE TITLE
Add `begin_block` function to contract

### ISSUE THREAD

**Issue by frankbraun** [aurora-is-near/aurora-engine#2]
For the [evm-bully](https://github.com/aurora-is-near/evm-bully) we need a `begin_block` function.
The `begin_block` function should allow to set the necessary block context the `evm-bully` needs to replay transactions successfully (see https://github.com/aurora-is-near/evm-bully/issues/3).
It should only be available in a testing version of the contract.

**Comment by artob** [comment]
@frankbraun Commits 3f15f0646c38ae841fa29ad0a6a9e5e73efe489f and 78c7c1f3d34b4da028cdf5f59a27bcf184494faf added the parameter definition for `begin_block`:

https://github.com/aurora-is-near/aurora-engine/blob/78c7c1f3d34b4da028cdf5f59a27bcf184494faf/src/types.rs#L50-L65

Note that the input to the `begin_block` function is Borsh-encoded, not JSON-encoded.

**Comment by frankbraun** [comment]
This needs to be put behind a feature flag and, as @ilblackdragon noted, should only be callable by the owner.

**Comment by artob** [comment]
> This needs to be put behind a feature flag and, as @ilblackdragon noted, should only be callable by the owner.

As of 529a751351ef8acf0360ef72c91a51eafb9ff01c, these methods are now only callable by the owner.

**Comment by joshuajbouw** [comment]
Isn't this closed now?

**Comment by artob** [comment]
@frankbraun Can this be closed? Please close issues when they are done.

**Comment by frankbraun** [comment]
The `evm-bully` calls `begin_block` with the correct arguments and they are decoded in the function in the contract:

https://github.com/aurora-is-near/aurora-engine/blob/51442811006a8803d2bcaaf6239e36eb2fb4eaaf/src/lib.rs#L364

However, the engine state is not updated correctly yet. @joshuajbouw, could you take a stab at this please? You are deeper into the engine. Might be related to #122

**Comment by joshuajbouw** [comment]
Yes, still looking into it.

**Comment by mrLSD** [comment]
@frankbraun  Is that Issue still should be open?

**Comment by joshuajbouw** [comment]
Considering that this functionality has been added and there are other issues that are in a succession of this, I'm going to close it.
