### ISSUE TITLE
Fix `block_hash`

### ISSUE THREAD

**Issue by joshuajbouw** [aurora-is-near/aurora-engine#209]
For EIP-1898, it requires polling of `block_hash`es which we do not support at this time.

Initially, @birchmd  submitted https://github.com/near/nearcore/pull/4273 for `nearcore` which returned the block hash from NEAR but how they and ETH does transactions could lead to issues. There likely is a better solution for this though which we can do on our end.

Per discussion and call, it has been decided that simply this needs to be returned:
```
sha256(concat(
    block_address_type_prefix, // e.g. 0xA
    near_block_height,
    chain_id,
))
```

* `block_address_type_prefix`: is a future proofing measure
* `near_block_height`: return from `sdk`'s `block_index`
* `chain_id`: Aurora's ETH chain ID.

**Comment by sept-en** [comment]
The suggestion for the block hash function:

```
sha256(concat(
    block_address_type_prefix, // e.g. 0xA
    near_block_height,
    chain_id,
))
```
