### ISSUE TITLE
Get Aurora ETH Faucet doesn't work well

### ISSUE THREAD

**Issue by think-in-universe** [aurora-is-near/aurora-engine#262]
The Aurora ETH Faucet (https://testnet.aurora.dev/faucet) said `It looks like you may already have enough Testnet ETH.` even if my account has no Aurora ETH.

![image](https://user-images.githubusercontent.com/46699230/132971063-d1416cb7-aa22-483a-a041-2dc368e6e55c.png)

**Comment by joshuajbouw** [comment]
I'll move this to https://github.com/aurora-is-near/aurora-webapp.

**Comment by think-in-universe** [comment]
@joshuajbouw Is this bug fixed? developers reported the bug again. 

It seems https://github.com/aurora-is-near/aurora-webapp is not accessible.
