### ISSUE TITLE
Overriding state in contract is not working.

### ISSUE THREAD

**Issue by mfornet** [aurora-is-near/aurora-engine#270]
The following solidity contract should replace the address of the sender on every `post` transaction but this only work the first time:

```sol
// SPDX-License-Identifier: LGPL-3.0-only
pragma solidity 0.8.7;

contract Poster {
    event NewPost(address indexed user, string content);
    
    address public sender_address;
    
    function post(string calldata content) public {
        sender_address = msg.sender;
        emit NewPost(sender_address, content);
    }
}
```

Steps to reproduce this error (I tested this on [Remix](https://remix.ethereum.org/). [See tutorial](https://doc.aurora.dev/develop/start/metamask)):
1. Deploy the contract
2. Check sender_address (result is `0x00000000000000000000000000000000000000`) This is expected.
3. Call `post` from address: `0x7eE858c1BdE9dc11E4531BF103c3245bCb3C2952`
4. Check sender_address (result is `0x7eE858c1BdE9dc11E4531BF103c3245bCb3C2952`). This is expected.
5. Call `post` from different address: `0x0c50003BDaAaf59597e1dA2815eD2cA0A4d98FE2 `
6. Check sender_address (result is `0x7eE858c1BdE9dc11E4531BF103c3245bCb3C2952`). **This is not expected**.

I expect on step 6) the `sender_address` to be equal to last used address (i.e. `0x0c50003BDaAaf59597e1dA2815eD2cA0A4d98FE2`).

In case it helps here tx from [step 3)](https://explorer.testnet.near.org/transactions/BUAp2qWPChMADQC2e36H2sv4wVz3AT1akEc3bP7EF5Wc) and [step 5)](https://explorer.testnet.near.org/transactions/5Dw1ug4Efmp1rnXHq1ZDR9SgJNKQYnjdyiVaDKxWcMmh).

This was [reported first here](https://t.me/auroraisneardev/1591).

**Comment by birchmd** [comment]
I was not able to reproduce this issue in a unit test, so I do not believe it is an engine issue. See #271

**Comment by mfornet** [comment]
I followed this steps using Firefox (instead of Brave) and it worked as expected, and in addition to the comment by @birchmd this indicates that this is not an issue in the engine. Closing this for now.
