### ISSUE TITLE
Expose NEAR's randomness host function as custom precompile

### ISSUE THREAD

**Issue by birchmd** [aurora-is-near/aurora-engine#297]
On Ethereum people need to use oracles for randomness (e.g. https://twitter.com/KamesCG/status/1446478366668955661). On NEAR there is a randomness host function we could expose as a custom precompile on Aurora, making it easier to access randomness.

This idea was proposed by @mikedotexe

**Comment by mikedotexe** [comment]
Even better than my idea, great stuff.
Here's the function from the Rust SDK side:
https://docs.rs/near-sdk/3.1.0/near_sdk/env/fn.random_seed.html

**Comment by birchmd** [comment]
Done in #368
