### ISSUE TITLE
Invalid low level EVM function `call` behaviour 

### ISSUE THREAD

**Issue by 0x3bfc** [aurora-is-near/aurora-engine#336]
The `call` (low level EVM function) should emit the callee contract address in the transaction logs, however it emits the caller contract address. The following example reproduces the issue:

```javascript
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract Caller {
    function greet(address to) public {
        to.call(abi.encodeWithSelector(Greeter(to).greet.selector));
    }
}


contract Greeter { // callee contract
    event Logger(address sender);

    function greet() public {
        emit Logger(msg.sender);
    }
}
```

***On Aurora testnet:*** 

By calling `Caller.greet()`, it returns the caller contract address in the transaction logs.

![image](https://user-images.githubusercontent.com/5428661/140892503-08e7c031-efd2-4fd4-9078-bf6b5b023821.png)

![image (1)](https://user-images.githubusercontent.com/5428661/140892559-65e7ecc0-135b-4b2c-82d3-6053edc0ba05.png)

***On Goerli testnet:*** 

![image](https://user-images.githubusercontent.com/5428661/140895471-dc1d15fe-f8f6-4024-985d-a9a222a33c39.png)
![image](https://user-images.githubusercontent.com/5428661/140895532-9dcd21d8-e901-47aa-b753-fbb57e3f3ba4.png)

`delegateCall` is working fine as expected (emitting the caller contract address in the logs). For more info please refer to [solidity docs](https://docs.soliditylang.org/en/v0.8.9/types.html?highlight=address.#members-of-addresses)

**Comment by joshuajbouw** [comment]
Thanks for finding this. We will look into determining if this is an issue with the engine or rust-blockchain EVM.
