### ISSUE TITLE
Standalone storage

### ISSUE THREAD

**Issue by joshuajbouw** [aurora-is-near/aurora-engine#370]
The standalone storage needs to be implemented into the engine as per the discussion in https://github.com/aurora-is-near/aurora-engine/discussions/328.

Specifically the below which has been snipped from the design for convenience:

### Storage implementation

The standalone engine will have its own storage implementation. The goal of this storage layer is to efficiently represent the EVM state from block to block. Here we describe a proposal for how the storage should be implemented.

I propose we use RocksDB as the underlying database. RocksDB is a key-value store with sorted keys to allow efficient range queries. Therefore the key layout is important. I propose we have the following key layout:

1. First byte is a version number (this will allow easy state migrations if needed). For now we will assume the version is 0.
2. Second byte is a column indicator. This allows iterating over specific data to be easy and efficient. The columns involved are detailed below.
3. Remaining bytes (if any) are data specific to the index of the values stored in that column. For example, a balances column for a specific block would have the block hash and address as the remaining bytes in the key (and obviously the balance as the value associated with that key).

I propose the database contain the following columns indicators (given in hex):

1. 00 = Block Hash. The index is 64-bit block height, the value is the block hash at that hight (for the block in the canonical chain). Note: most other information will be indexed by block hash so that if a re-org occurs then those columns do not need modifications, only additions. This column will need to be modified with the new hashes at each height. The column indexed by transaction hash (02) will also need to be modified.
2. 01 = Block Height. The index is the 32-byte block hash, the value is the block height. Note: this column does not need to change in the case of a re-org because each block remains at its associated height, it just may no longer be part of the canonical chain.
3. 02 = Transaction Position. The index is a 32-byte transaction hash, the value is `(BlockHash, u16)`, which represents the block and position in that block where the transaction was included. If the transaction was included in multiple blocks, then the one which is in the canonical chain is given as the value. This means this column must be modified in the case of a re-org.
4. 03 = Transaction Hash. The index is a 32-byte block hash + a 16-bit position index, the value is a transaction hash. This allows looking up the transactions which were included in a given block.
5. 04 = Diff. The index is a 32-byte block hash + a 16-bit position index, the value is the state diff the transaction executed in that block at that position caused. A state diff has the same data as is produced by a transaction execution in SputnikVM. These state diffs can be used to derive the state at any transaction from some sparse snapshots.
6. 05 = Balances. The index is a 32-byte block hash + a 20-byte address, the value is the 256-bit ETH balance. Only non-zero balances are stored. The purpose of this column is to provide a part of the state snapshot at a given block. This column will not be populated for all blocks, only a subset (say every 50 blocks), and state for other blocks will be derived from these snapshots using diffs.
7. 06 = Nonces. The index is a 32-byte block hash + a 20-byte address, the value is the 256-bit ETH nonce. Only non-zero nonces are stored. Just like the balances column, the purpose of this is occasional snapshotting of the state.
8. 07 = code. The index is a 32-byte block hash + a 20-byte address, the value is the EVM bytecode deployed at that address. Only non-zero values are stored. Just like the previous two column, the purpose of this is occasional snapshotting of the state.
9. 08 = Storage. The index is a 32-byte block hash + a 20-byte address + a 32-byte storage key, the value is a `[u8; 32]`. Only non-zero values are stored. Just like the previous three columns, this is used for snapshotting.

#### High level storage interface

The interface to interact with this storage layer will be as follows:

```rust
// getters

struct State<'a> { ... }
impl State {
    fn get_nonce(&self, address: Address) -> U256;
    fn get_balance(&self, address: Address) -> Wei;
    fn get_storage_at(&self, address: Address, key: H256) -> H256;
}

struct BasicAccountInfo {
    balance: Wei,
    nonce: U256,
    has_code: bool,
}

impl Storage {

    /// Returns an object able to get values from the pre-state of the given block + transaction index.
    /// (Pre-state means the transactions _at_ the given index has not yet been applied).
    fn get_state<'a>(&'a self, block_hash: H256, tx_position: u16) -> Result<State<'a>, Error>;

    /// Return all non-empty accounts in the post-state of the given block
    fn get_accounts(&self, block_hash: H256) -> Result<Map<Address, BasicAccountInfo>, Error>;
    
    /// Returns all accounts that were modified in some way by transactions in blocks between
    /// the two given blocks. Returns an error if the blocks are no in the canonical chain.
    /// The information returned is that of the post-state of the given end block.
    fn get_changed_accounts(&self, start_block_hash: H256, end_block_hash: H256) -> Result<Map<Address, BasicAccountInfo>, Error>;
}

// setters

struct AccountInfo {
    balance: Wei,
    nonce: U256,
    code: Vec<u8>,
    storage: Map<H256, H256>,
}

impl Storage {

    /// Consumes a NEAR transaction and updates the storage; requires the engine to get
    /// the diff from executing the transaction.
    fn submit_transaction(&mut self, block_hash: H256, block_height: u64, tx: Transaction, tx_position: u16, engine: &Engine) -> Result<(), Error>;

    /// Bootstrap the state by directly submitting a snapshot for some block
    /// (can then apply transactions to this state to get future states)
    fn submit_snapshot(&mut self, block_hash: H256, state: Map<Address, AccountInfo>)
    
}
```

##### Replay given transaction

1. Look up what block the tx was executed in using column 02.
2. Look up the height of this block using column 01.
3. Check the hash at this height in column 00 matches the hash where the tx is executed (ie the tx was included in the canonical chain). If it was not then throw an error. TODO: we could probably support replay of orphaned transactions, but finding the right snapshot to start from would be much more computationally intensive, and I think this is probably a rare enough use case that it is ok to not support it initially.
4. Look up the blockhash for the closest snapshot prior to the height where the tx was executed. If we have some very regular scheme for snapshotting (eg every 50 blocks), it is easy to determine which height the snapshot would be at and get the hash from column 00. Note: this does rely on the transaction being included in the canonical chain.
5. Look up the diffs for all the transactions in all the blocks between the snapshot and the target transaction. Merge these into a single diff (this can be done because there is a natural algebra of diffs).
6. To look up any value in the state during the transaction replay (eg a balance or nonce), find it in the snapshot and modify based on the merged diff if needed.

##### Tracking addresses and balances

Getting a list of addresses with non-zero nonce (or really any nonce) bound is trivial by simply iterating over some block in column 06. Similarly for balances with column 05. Moreover, the diffs could be used to see only the new accounts and balances between two blocks. This could be useful for analytics or more advanced relayer rate-limiting.

**Comment by birchmd** [comment]
This is done. Code available at https://github.com/aurora-is-near/aurora-engine/tree/master/engine-standalone-storage
