### ISSUE TITLE
nETH ft_transfer_call doesn't attach enough gas to ft_on_transfer

### ISSUE THREAD

**Issue by evgenykuzyakov** [aurora-is-near/aurora-engine#381]
The `aurora` contract on NEAR side attaches fixed number of `10 TGas` only:

https://github.com/aurora-is-near/aurora-engine/blob/d020887ca3a9390843e3f6ea034e46e3d11c0f1f/engine/src/fungible_token.rs#L13

The standard implementation is uses the following logic, which allows to provide more than `10 TGas`:

https://github.com/near/near-sdk-rs/blob/7676fda0bc7e93ae809f66878f51144c98bcc974/near-contract-standards/src/fungible_token/core_impl.rs#L180

Even though it's not ideal due to limit on the `msg` size, it allows to provide larger amount of gas for the remote contract.

**Comment by joshuajbouw** [comment]
In our pipeline.

**Comment by mrLSD** [comment]
@evgenykuzyakov thanks for that point.
I see, by the link summary is `30 TGas`.
