### ISSUE TITLE
Investigate gas usage with state trie depth

### ISSUE THREAD

**Issue by joshuajbouw** [aurora-is-near/aurora-engine#394]
@birchmd found and issue with the gas usage with state trie depth.

We had a report from a user that a contract call that was previous working now suddenly is not anymore. Now they are hitting the 200 TGas limit. @birchmd determined that `TOUCHING_TRIE_NODE` is a significant contributor to this substantial gas usage. Estimating as much as 36% of the gas cost of the transaction.

In our benchmarks, we do not see this as our state trie is fresh, resulting in a 0 gas cost. NEAR core has a RS testing framework which was recommended to us to use and to contact @ChaoticTempest about that.

## What we do know:
- Costs of touching the state trie haven't been raised.
- Not related to sharding since NEAR moved us onto a single shard.
- The costs did in fact go down a little bit post moving to a single shard after block 52890665 on NEAR.
- Not related to Aurora contract updates

## What we don't know:
- If the costs increased after we moved to a single shard post block 52890665 on NEAR
- If it is related to a NEAR upgrade, which inadvertently raised the cost

## References:
- User submits a transaction which is successful: https://explorer.mainnet.near.org/transactions/4UaCrSUYRJuZ8YnNQoQvQwYYXXpRQAcqSxqzaYkT4xgC
- User submits a similar transaction which is unsuccessful indicating costs went up: https://explorer.mainnet.near.org/transactions/9i8xvpQqNv536sZnZsL64houaDxfYxcw7qM8jNF5fbff
- This discussion may resolve this issue: https://github.com/near/nearcore/discussions/4815
- This PR can be used to track depths before and after lookups: https://github.com/near/nearcore/pull/5722

**Comment by rej156** [comment]
Can report the same issue with Necc Protocol transactions

**Comment by birchmd** [comment]
NEAR has trie node caching since protocol version v53. This should no longer be an issue.
