### ISSUE TITLE
Fill in the backend engine implementation.

### ISSUE THREAD

**Issue by joshuajbouw** [aurora-is-near/aurora-engine#43]
The engine implementation is sparse and filled with quite a bit of dummy data. This may take a bit of research to find the correct or similar methods on NEAR.

See `impl evm::backend::Backend for Engine {` in `engine.rs`

**Comment by artob** [comment]
@joshuajbouw Did you have something remaining to do on this, or can it be closed?

**Comment by joshuajbouw** [comment]
Yeah this can be closed as after review and this being the only result https://github.com/aurora-is-near/aurora-engine/pull/47, its fine.
