### ISSUE TITLE
Move EthTransaction-like types to aurora-types crate

### ISSUE THREAD

**Issue by mfornet** [aurora-is-near/aurora-engine#430]
Several tools from our stack may benefit from using the same types from the engine directly to parse transactions that were submitted to aurora. This way we maintain types in a single place, and all de/serialization is inherited.

**Comment by birchmd** [comment]
https://github.com/aurora-is-near/aurora-engine/tree/develop/engine-transactions/src does not meet this requirement?

**Comment by mfornet** [comment]
Absolutely, I missed it, and thought they were part of the same crate as aurora-engine.
