### ISSUE TITLE
Better mechanism for capturing gas usage in benchmarks

### ISSUE THREAD

**Issue by birchmd** [aurora-is-near/aurora-engine#45]
In https://github.com/aurora-is-near/aurora-engine/pull/41 gas usage of the benchmarks is simply reported to the terminal. This makes capturing the data and analyzing it a manual process, which is sub-optimal.

The goal of this issue is to find a better way to capture the gas usage data, and to combine it with the timing data automatically in order to draw conclusions.

One possibility might be to use a [custom measurement](https://bheisler.github.io/criterion.rs/book/user_guide/custom_measurements.html) in `criterion` itself.

**Comment by artob** [comment]
Related PR in the works: https://github.com/aurora-is-near/aurora-engine/pull/48

**Comment by joshuajbouw** [comment]
Can close as of https://github.com/aurora-is-near/aurora-engine/pull/48.
