### ISSUE TITLE
RPC error

### ISSUE THREAD

**Issue by p2pvid** [aurora-is-near/aurora-engine#450]
While running my solidity smart contract on aurora , I am getting RPC error sometimes..

This error isn't every time.. This comes sometimes,, not sure why.. Attaching the screenshot

![image](https://user-images.githubusercontent.com/77237676/154637976-4b4693cb-dcc4-4626-9943-f76e9901cbe9.png)

**Comment by joshuajbouw** [comment]
This is a relayer issue, see the note where to report the error. Thanks.
