### ISSUE TITLE
Random ERR_INCORRECT_NONCE errors

### ISSUE THREAD

**Issue by CodeMocsh** [aurora-is-near/aurora-engine#451]
Hey folks, I see random ERR_INCORRECT_NONCE errors on smart contract calls on mainnet: what could be going wrong?

(body="{\"jsonrpc\":\"2.0\",\"id\":110,\"error\":{\"code\":-32000,\"message\":\"ERR_INCORRECT_NONCE\",\"data\":{\"host\":\"[r005.eastcoast.us.relayer.internal.aurora.dev](https://r005.eastcoast.us.relayer.internal.aurora.dev/)\",\"cf-ray\":\"6df3de94020c2548-IAD\"}}}", error={"code":-32000,
....

**Comment by joshuajbouw** [comment]
Simply you are submitting transactions that have an incorrect nonce value. Ensure that it is correct. If the account's nonce value is say, 240, then you must increment it by 1 to 241 for it to be successful.

**Comment by CodeMocsh** [comment]
thanks, Is any special handing needed to manage the nonce on aurora?
I just use ethers.Contract, and ethers.Wallet APIs

**Comment by joshuajbouw** [comment]
Sorry about the delayed response. Given the emergency in Ukraine. Namely, just got to ensure that the nonce is correctly incrementing. Are there multiple transactions happening in a block?

**Comment by joshuajbouw** [comment]
I'm going to flag this on our relayer. There are ways we can improve this there, which we can not improve on the Engine as it'll process transactions sequentially, which the relayer must do.

**Comment by mb-gvidon** [comment]
@joshuajbouw same problem as in https://github.com/aurora-is-near/aurora-engine/issues/451#issuecomment-1112453246

I have sent the link to my (half-failed) transaction to your email [joshua@aurora.dev](mailto:joshua@aurora.dev)

**Comment by Younghoon-Lee** [comment]
@strange-dv  you can handle this issue by manually managing nonce when you are sending transactions.

**Comment by Umar-Abbas** [comment]
try this 
it will work
 let myNonce =await web3.eth.getTransactionCount(myPublicAddress)
let NetxNonce= web3.utils.toHex(myNonce++)
