### ISSUE TITLE
Frequent 403 from testnet for trivial amounts of traffic

### ISSUE THREAD

**Issue by brian-man** [aurora-is-near/aurora-engine#453]
Until yesterday, Aurora testnet was flaky for me but I could get some functionality to work.

Yesterday mid-day I started getting
`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://testnet.aurora.dev/`
pretty much instantly when trying to interact with the chain.

In response, I ignored the chain for at least 12 hours.  Within 30 seconds, I get 403 again attempting a handful of requests.

Is it down or am I holding it wrong?

Are there other public nodes to use besides `https://testnet.aurora.dev/`?

Thanks.

---

Example 1:
9 requests => 403
```
vars(uint256)
getPartnerProject(uint256)
decimals()
name()
getPartnerProject(uint256)
vars(uint256)
userVars(address,uint256)
balanceOf(address)
tokenOfOwnerByIndex(address,uint256)
```
---
Example 2:
1 request => 403
```
vars(uint256)
```

**Comment by joshuajbouw** [comment]
Not related to the engine, related to https://github.com/aurora-is-near/aurora-relayer. Or more so, the infrastructure of it. However, I do not believe that this is a continual issue today. If it is, best to reopen there.
