### ISSUE TITLE
Update near_blake2 to latest interface 

### ISSUE THREAD

**Issue by mfornet** [aurora-is-near/aurora-engine#464]
I was struggling with this issue recently, up to the point where I got to [near-blake2](https://github.com/near/near-blake2) repository just to found out that blake2b_f function is no longer a thing over there.
It was changed on [this commit](https://github.com/near/near-blake2/commit/0a21d378670234e943d7efcc79e0b85629c99f57). 

The problem is that when pulled aurora-engine as a library Cargo.lock is recreated and it uses the most recent version which [is not compatible with our current code](https://github.com/aurora-is-near/aurora-engine/blob/master/engine-precompiles/src/blake2.rs#L97). In the mean time I updated manually my Cargo.lock file to unblock me.

**Comment by joshuajbouw** [comment]
Thanks for the report, had the same issue as have others.

**Comment by joshuajbouw** [comment]
Can be closed due to: https://github.com/aurora-is-near/aurora-engine/pull/528
