### ISSUE TITLE
metamask shows 'Could not fetch chain ID. Is your RPC URL correct?'

### ISSUE THREAD

**Issue by kulame** [aurora-is-near/aurora-engine#487]
i try to Connecting MetaMask to Aurora
and follow this docs  https://doc.aurora.dev/interact/metamask
when i Fill in the form with the Chain ID: 1313161555
the metamask tell me 'Could not fetch chain ID. Is your RPC URL correct?'

what's wrong with this?

**Comment by kulame** [comment]
i try to visit the 'https://testnet.aurora.dev/' website. it returns 

```

Access denied Error code 1020

You do not have access to testnet.aurora.dev.

The site owner may have set restrictions that prevent you from accessing the site. Contact the site owner for access or try loading the page again.

```

any restriction on testnet.aurora.dev?

**Comment by birchmd** [comment]
@kulame this error results from hitting the request rate limit on the RPC. You will need to provide us with your IP address to get unblocked. The rate limit is 1000 requests per minute, please stay within that threshold in the future.
