### ISSUE TITLE
unable to pass argument to a function while calling using aurora cli

### ISSUE THREAD

**Issue by TanyaSrivastava-Dipali** [aurora-is-near/aurora-engine#512]
How to pass functional argument while calling any setter function using aurora cli?

Example
for this contract

// SPDX-License-Identifier: MIT
pragma solidity >=0.4.0 <0.7.0;
contract SimpleStorage {
    uint storedData;
    function set(uint x) public {
        storedData = x;
    }
    function get() public view returns (uint) {
        return storedData;
    }
}

I'm able to get the value by this command-
aurora --network testnet --signer tanyasrivastava.testnet  view --sender 0xF52B35879fE693bca630cd136038DC53Dc42A169 0x88e6897991ce4b21846fa14ca257bccffdf7311c 0x6d4ce63c

but unable to set the value by below command 
 aurora --network testnet --signer tanyasrivastava.testnet call  0x88e6897991ce4b21846fa14ca257bccffdf7311c 0x60fe47b1

anyone plesase suggest how to give argument in avove command to set the value.

**Comment by birchmd** [comment]
What error are you getting? The command you provided worked fine for me.

```
aurora-is-near/aurora-cli$ ./lib/aurora.js --network testnet --signer birchmd.testnet call 0x88e6897991ce4b21846fa14ca257bccffdf7311c 0x60fe47b1

Receipt: 4DXqPMaQUGAgHBCJZ5mR8JGKNisVJ7cDo9fzQMsUBVq9
        Log [aurora]: total_writes_count 2
        Log [aurora]: total_written_bytes 64
┌────────────────────────────────────────────┬────────────┬────────────────────────────────────────┐
│                                   contract │     inputs │                                 output │
├────────────────────────────────────────────┼────────────┼────────────────────────────────────────┤
│ 0x88e6897991ce4b21846fa14ca257bccffdf7311c │ 0x60fe47b1 │ 0x070100000000d75200000000000000000000 │
└────────────────────────────────────────────┴────────────┴────────────────────────────────────────┘
```

**Comment by TanyaSrivastava-Dipali** [comment]
Thanks for your response.
This is also working for me but It's not setting any value to storedData variable.
after executing the same command what you ran if i execute command for get function i get 0 as output.

aurora --network testnet --signer tanyasrivastava.testnet  view --sender 0xF52B35879fE693bca630cd136038DC53Dc42A169 0x88e6897991ce4b21846fa14ca257bccffdf7311c 0x6d4ce63c

value is not being set .
my question is that how can we pass argument to set value of storedata variable using the command what you executed.

Once again Thanks a lot!

**Comment by karim-en** [comment]
You need to encode the <input> data correctly, this could be done by using web3js https://web3js.readthedocs.io/en/v1.2.11/web3-eth-abi.html#encodefunctioncall
or manually:
function_signature + encoded_args
If you want to get encoded function signature of the function sendMessage(string message, address to) , hash prototype string of the function sendMessage(string,address) with Keccak256. Then extract the first 4bytes “0xc48d6d5e”.
To encode the args you can use this https://adibas03.github.io/online-ethereum-abi-encoder-decoder/#/encode

Example of erc20 approve(spender, amount) call:
aurora --network testnet --signer tanyasrivastava.testnet call 0x88e6897991ce4b21846fa14ca257bccffdf7311c 0x095ea7b3000000000000000000000000c4c5708fae3028b98931ecb9e7151ce1fb9f392f0000000000000000000000000000000000000000000000000000000000000014

**Comment by birchmd** [comment]
Exactly what @karim-en said.

In your example @TanyaSrivastava-Dipali you were only passing the selector bytes with no other input, so you were always setting the `storedData` to 0. If you include 32 bytes after the function selector then the data will be set. For example if I use the command

```
aurora-is-near/aurora-cli$ ./lib/aurora.js --network testnet --signer birchmd.testnet call 0x88e6897991ce4b21846fa14ca257bccffdf7311c 0x60fe47b10000000000000000000000000000000000000000000000000000000000000007
Receipt: EUYxwztgBiX6yRdWdQWEpRoQntCp5a66yKXW8gbVpjpo
        Log [aurora]: total_writes_count 5
        Log [aurora]: total_written_bytes 160
┌────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────┐
│                                   contract │                                                                     inputs │                                 output │
├────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────┤
│ 0x88e6897991ce4b21846fa14ca257bccffdf7311c │ 0x60fe47b10000000000000000000000000000000000000000000000000000000000000007 │ 0x070000000000386700000000000000000000 │
└────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────┘
```

Notice in the logs there are more bytes written than in my previous example, this is because the storage was actually updated.

Unfortunately, `aurora-cli` is not properly maintained any more, so you cannot see the stored value easily using that tool. In my spare time I have been working on a new CLI for Aurora written in Rust: https://github.com/birchmd/aurora-cli-rs

Using this tool you can view the stored data to see it is correct:

```
birchmd/aurora-cli-rs$ cargo run -- --network testnet contract-view --target-addr-hex 88e6897991ce4b21846fa14ca257bccffdf7311c --input-data-hex 6d4ce63c
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/aurora-cli-rs --network testnet contract-view --target-addr-hex 88e6897991ce4b21846fa14ca257bccffdf7311c --input-data-hex 6d4ce63c`
Succeed([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7])
```

Notice it is a 32-byte array with the last byte being 7, which is exactly what I sent in my call command.
