### ISSUE TITLE
Aurora engine integration with web3/ ethers.js

### ISSUE THREAD

**Issue by Ashish-Khatri8** [aurora-is-near/aurora-engine#556]
Hi
I want to use ethers.js or web3.js to interact with the aurora engine directly.
Is there a way to achieve this?
If yes, could you please provide any docs or tips on how to do this.
Thank You

**Comment by birchmd** [comment]
There is no way to directly interact with the engine using one of these libraries. The code here is for the smart contract on Near which contains the EVM logic. To interact with it using the Ethereum RPC you will need to run a "relayer" which translates web3 calls into Near calls to the engine. See https://github.com/aurora-is-near/aurora-relayer
