### ISSUE TITLE
The pre-contract (0x5) has incorrect logic on calculating the gas fee

### ISSUE THREAD

**Issue by valour01** [aurora-is-near/aurora-engine#631]
**The Issue content described potential security vulnerability and is NOT to be public before a fix is implemented. The content will be returned once patched. Thank you for understanding.**

**Comment by joshuajbouw** [comment]
Closeed in https://github.com/aurora-is-near/aurora-engine/commit/d9b911187b20b931610a02ed8a5670a0462b87b5.
