### ISSUE TITLE
HttpProviderError error while deploying with hardhat

### ISSUE THREAD

**Issue by prasad-kumkar** [aurora-is-near/aurora-engine#635]
Facing this issue while deploying, tried changing multiple other RPCs (infura, etc), but still the same error
<img width="522" alt="image" src="https://user-images.githubusercontent.com/43164022/200516429-15afdd9a-5abc-4164-9d3e-13e4478f4656.png">

Network config:
```
aurora_testnet: {
      url: "https://testnet.aurora.dev",
      accounts: ["0x" + process.env.PRIVATE_KEY],
    },
```

**Comment by joshuajbouw** [comment]
Not related to the EVM. Related to the relayer. @pustovalov
