### ISSUE TITLE
Understanding precompiles return value

### ISSUE THREAD

**Issue by mfornet** [aurora-is-near/aurora-engine#64]
It is hard to tell from [this tuple](https://github.com/aurora-is-near/aurora-engine/blob/master/src/precompiles/mod.rs#L19): `type PrecompileResult = Result<(ExitSucceed, Vec<u8>, u64), ExitError>;` what does the last value (`u64`) means. I'm assuming that second value `Vec<u8>` is the output.

Could you clarify what does the last value means?

Also consider changing this tuple to a named struct and/or add some comments documenting this.

**Comment by joshuajbouw** [comment]
Yeah, so this is the interface from the Sputnik VM itself. We can not exactly change it. However, that last value should be `cost`, which is an issue, as we are returning 0 for now, but we also are not charging gas at the moment. The cost is returned, and then it is recorded.

This certainly should be fixed.
