### ISSUE TITLE
EVM Flashloan on Aurora. but get "A status code indicating if the top-level call succeeded or failed (applicable for Post BYZANTIUM blocks only)

### ISSUE THREAD

**Issue by cklai90** [aurora-is-near/aurora-engine#642]
I am had successfully deploy a flashloan contract on both Aurora & Aurora+ network (an EVM on Near protocol).

and also successfully tested with its RPC on hardhat, there are no issues, able to borrow and return fund.

However, when executing on mainnet, it shows a failed transaction with the following error:
"A status code indicating if the top-level call succeeded or failed (applicable for Post BYZANTIUM blocks only).

what could be the possible root cause?

here is a link to aurora [scan](https://aurorascan.dev/tx/0xc39664c8376d05f7cbd572b7ce9fcf3fc754b0af344a1242109f9f725b348a40).

**Comment by birchmd** [comment]
Hi @cklai90 , thanks for the report. Unfortunately, aurorascan currently does not do a good job at reporting error messages. To get the reason for a transaction failure, we recommend using our RPC. For example, with this transaction you could use `debug_traceTransaction` to see the error reason and output (as well as the full call trace if you are interested in that). Below is an example of using our RPC (accessed via the [HTTPie](https://httpie.io/) CLI) to debug this transaction.

```
$ http post https://mainnet.aurora.dev/ jsonrpc=2.0 id=1 method=eth_getTransactionReceipt params:='["0xc39664c8376d05f7cbd572b7ce9fcf3fc754b0af344a1242109f9f725b348a40"]' | jq .result.error

"Revert(Reverted)"

$ http post https://mainnet.aurora.dev/ jsonrpc=2.0 id=1 method=eth_getTransactionReceipt params:='["0xc39664c8376d05f7cbd572b7ce9fcf3fc754b0af344a1242109f9f725b348a40"]' | jq .result.output

"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000018417262697472616765206e6f742070726f66697461626c650000000000000000"
```

From this we can see that your contract reverted with the error message `Arbitrage not profitable`. What this means depends on what you were trying to do, but at the very least I can say that it is not an issue with the Aurora Engine itself. Therefore, I will close this issue.

**Comment by cklai90** [comment]
cool tools, many thanks! gonna keep in my library
