### ISSUE TITLE
`make check` failing due to wasmer error

### ISSUE THREAD

**Issue by lightyagamoon** [aurora-is-near/aurora-engine#66]
Getting the following error when trying to run `make check` on a MacBook Air (M1, 2020)

```
error[E0425]: cannot find function `get_fault_info` in this scope
   --> /Users/rootling/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-runtime-core-near-0.17.1/src/fault.rs:289:21
    |
289 |         let fault = get_fault_info(siginfo as _, ucontext);
    |                     ^^^^^^^^^^^^^^ not found in this scope

   Compiling wasmer-compiler v1.0.2
   Compiling near-vm-errors v3.0.0
   Compiling cranelift-frontend v0.67.0
error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: could not compile `wasmer-runtime-core-near`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by joshuajbouw** [comment]
That isn't an issue of this repo, you can see that it is an issue of `wasmer-runtime-core-near`. I figure that very likely is because there are conditional compilation flags that do not yet deal with M1 Macbook. [Please raise the issue there.](https://github.com/wasmerio/wasmer/issues/new/choose)

**Comment by birchmd** [comment]
See also https://github.com/near/nearcore/issues/3803 (this is an issue about supporting M1 in `nearcore`, which is one of our dependencies used in tests).
