### ISSUE TITLE
Newtype for balances in EVM

### ISSUE THREAD

**Issue by birchmd** [aurora-is-near/aurora-engine#67]
It's easy to accidentally mess up amounts in EVM, even for experts like ourselves (e.g. https://github.com/aurora-is-near/aurora-engine/pull/57#discussion_r629353860 ). Also, `U256` represents lots of different (not interchangeable) quantities: account nonces, account balances (in Wei), ERC20 token balances (of various sorts!), etc.

To make sure we get account balances right we should have a newtype to represent amounts in Wei, and ensure all function arguments that represent balances use this type. It should also include convenience functions for unit conversion.

E.g.

```rust
pub struct Wei(U256);

impl Wei {
    const ETH_TO_WEI: U256 = U256::from(1_000_000_000_000_000_000);

    pub fn new(amount: U256) -> Self {
        Self(amount)
    }

    pub fn from_eth(amount: U256) -> Option<Self> {
        amount.checked_mul(Self::ETH_TO_WEI).map(Self)
    }
}
```

**Comment by joshuajbouw** [comment]
As discussed privately, yeah this makes sense to add in as Newtypes are powerful enough that nobody would be able to make a mistake with them, nor use them interchangeably with other values.

**Comment by birchmd** [comment]
Done in #96 (I guess the issue didn't automatically close because it merged into `develop` instead of `master`?)
