### ISSUE TITLE
Implement Berlin HF support

### ISSUE THREAD

**Issue by artob** [aurora-is-near/aurora-engine#8]
Tracking issue for Berlin HF support.

- [x] [EIP-2565] - PR https://github.com/aurora-is-near/aurora-engine/pull/138
- [x] [EIP-2718] - PR https://github.com/aurora-is-near/aurora-engine/pull/165
- [x] [EIP-2929] - PR https://github.com/rust-blockchain/evm/pull/40, https://github.com/rust-blockchain/evm/pull/40
- [ ] [EIP-2930] - PR https://github.com/rust-blockchain/evm/pull/40, https://github.com/rust-blockchain/evm/pull/40

[EIP-2565]: https://eips.ethereum.org/EIPS/eip-2565
[EIP-2718]: https://eips.ethereum.org/EIPS/eip-2718
[EIP-2929]: https://eips.ethereum.org/EIPS/eip-2929
[EIP-2930]: https://eips.ethereum.org/EIPS/eip-2930

**Comment by joshuajbouw** [comment]
First one is here: https://github.com/aurora-is-near/aurora-engine/pull/138

**Comment by joshuajbouw** [comment]
Closing as all tasks are complete.
