### ISSUE TITLE
chore: publish `aurora-engine-modexp` crate

### ISSUE THREAD

**Issue by rakita** [aurora-is-near/aurora-engine#844]
Can we get `aurora-engine-modexp` published to crates, I would like to use it inside `revm` and I see that is not available in crates.io.

**Comment by rakita** [comment]
I have published the lib with some minor [changed](https://github.com/rakita/aurora-engine/tree/master-publish) to the [crates](https://crates.io/crates/aurora-engine-modexp) to unblock the integration

Would be happy to transfer the ownership if needed

**Comment by aleksuss** [comment]
Thanks for the publishing. It would be nice if you transferred the ownership.

**Comment by rakita** [comment]
> Thanks for the publishing. It would be nice if you transferred the ownership.

Who should I add as an owner?

**Comment by aleksuss** [comment]
@birchmd and @aleksuss please.

**Comment by aleksuss** [comment]
@rakita Thanks!

**Comment by rakita** [comment]
Will close this now as the crate is published. And thank you for the work on the lib!

I can stay as an owner or you can remove me I am fine with both, it is really about your preferences.
